---
title: "SCORE Preprint Module Repository"
listing:
  id: preprint-modules
  page-size: 10
  contents:
    - "*/*/index.qmd"
  sort: date desc
  image-placeholder: "_img/default_thumbnail.png"
  fields: [image, title, author, date, categories, description]
---

The [SCORE Network](https://scorenetwork.org/index.html) Module Repository enables you to search for modules by either sport or by statistics and data science topic.

Please note that the modules listed in this repository have not yet completed the required pedagogical and industry peer reviews to become a published module on the SCORE Network.

Instructors and students are still welcome to use these preprints. Additionally, if you use them and have feedback for the authors, please contact [scorenetworkorg@gmail.com](mailto:scorenetworkorg@gmail.com).


## All Modules

::: {.callout-note appearance="minimal"}
Browse all modules below. Use the sidebar to filter by sport or visit [by statistics and data science topic](by-statsds-topic.qmd).
:::

::: {#preprint-modules}
:::


## Contributing and/or Joining the SCORE Network

Interested in submitting your own module? [Click here to find out more information about the SCORE Network module submission process.](https://scorenetwork.org/submissions.html)


## Funding Source

*The development of the SCORE with Data network is funded by the National Science Foundation (award 2142705).* 

